<?php

namespace CitiesBundle\Repository;

/**
 * CountryLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryLanguageRepository extends \Doctrine\ORM\EntityRepository
{
}
